
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from tkinter import Frame, Canvas, Entry, Button, PhotoImage
from pathlib import Path

ASSETS_PATH = Path(__file__).parent.parent / "build" / "assets" / "frame01"

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class RegistrationWindow(Frame):
    def __init__(self, parent, switch_to_login):
        super().__init__(parent)
        self.configure(bg="#FFFFFF")
        self.place(x=0, y=0, relwidth=1, relheight=1)

        self.switch_to_login = switch_to_login


        canvas = Canvas(
            self,
            bg = "#FFFFFF",
            height = 668,
            width = 1094,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            1180.0,
            741.0,
            fill="#EEE2DC",
            outline="")

        canvas.create_text(
            171.0,
            135.0,
            anchor="nw",
            text="Регистрация",
            fill="#AC3B61",
            font=("InknutAntiqua Regular", 48 * -1)
        )

        canvas.create_text(
            138.0,
            66.0,
            anchor="nw",
            text="Gameback",
            fill="#AC3B61",
            font=("Inter Bold", 72 * -1)
        )

        canvas.create_rectangle(
            106.0,
            232.0,
            493.0,
            606.0,
            fill="#EDC7B7",
            outline="")

        canvas.create_text(
            145.0,
            442.0,
            anchor="nw",
            text="Повторите пароль",
            fill="#123C69",
            font=("Inter", 16 * -1)
        )

        entry_1 = Entry(self,
            bd=2,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_1.place(
            x=153.0,
            y=385.0,
            width=283.0,
            height=35.0
        )

        entry_2 = Entry(self,
            bd=2,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_2.place(
            x=153.0,
            y=474.0,
            width=283.0,
            height=35.0
        )

        canvas.create_rectangle(
            590.0,
            17.0,
            1180.0,
            758.0,
            fill="#EDC7B7",
            outline="")


        entry_3 = Entry(self,
            bd=2,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_3.place(
            x=153.0,
            y=299.0,
            width=283.0,
            height=35.0
        )

        canvas.create_text(
            146.0,
            259.0,
            anchor="nw",
            text="Имя",
            fill="#123C69",
            font=("Inter", 16 * -1)
        )

        canvas.create_text(
            145.0,
            353.0,
            anchor="nw",
            text="Пароль",
            fill="#123C69",
            font=("Inter", 16 * -1)
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))  # Сохраняем изображение
        button_1 = Button(
            self,  # Родитель — текущий фрейм
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=self.switch_to_login,  # Функция возврата
            relief="flat"
        )
        button_1.place(
            x=146.0,
            y=531.0,
            width=299.0,
            height=40.0
        )

